const medicamentos1 = [
    { nombre: "Paracetamol Tableta, 500 Mg Oral", disponible: 1226 },
{ nombre: "Butimaxil Dicloxacilina, Suspensión 250mg/5ml", disponible: 589 },
{ nombre: "Bruzol Albendazol Suspensión 2g / 100ml Frasco Con 20ml", disponible: 567 },
{ nombre: "Fumarato Ferroso Tableta 200mg", disponible: 566 },
{ nombre: "Soltrim Trimetoprima, Sulfametoxazol, Tableta 80 Mg, 400 Mg Oral", disponible: 549 },
{ nombre: "Avidal 500 Metronidazol Tabletas 500mg Oral", disponible: 500 },
{ nombre: "Metronidazol Biotazol Taleta 500 Mg", disponible: 452 },
{ nombre: "Miconazol Crema, Tubo Con 20 G", disponible: 435 },
{ nombre: "Butimaxl Dicloxacilina, Cápsulas 500 mg", disponible: 408 },
{ nombre: "Clavipen Amoxicilina, Ácido Clavulanico Suspensión, 125mg, 31.25 Mg/5 Ml", disponible: 377 },
{ nombre: "Metronidazol Tableta 500 Mg Vaginal", disponible: 364 },
{ nombre: "Hidróxido De Aluminio, Hidróxido De Magnesio 240 ml Solfran", disponible: 361 },
{ nombre: "Metronidazol Suspensdión 250 Mg/5 Ml Oral", disponible: 299 },
{ nombre: "Bencilpenicilina Procainica Con Bencilpenicilina Critalina Suspensión 400,000 UI Inyectable", disponible: 295 },
{ nombre: "Enalapril Tabletas 10mg", disponible: 285 },
{ nombre: "Derimeton Clorfenamina Jarabe, 50 Mg/100 Ml Frasco Con 60 Ml", disponible: 265 },
{ nombre: "Trimetroprima/Sulfametoxazol, Suspensión 0.8g/4.0g, 120 Ml Oral", disponible: 252 },
{ nombre: "Fenitoina Biodan Tableta 100 Mg", disponible: 237 },
{ nombre: "Valdefer Sulfato Ferroso Tabletas 200 Mg, Oral", disponible: 228 },
{ nombre: "Miconazol Crema 2 % ALPHARMA", disponible: 224 },
{ nombre: "Itraconazol Capsulas 100.0 Mg", disponible: 222 },
{ nombre: "Metoclopramida Solución Oral 400 Mg", disponible: 217 },
{ nombre: "ODLIVIR Isoconazol Crema 1 G / 100 G Cutánea", disponible: 214 },
{ nombre: "Plantago Psyllium, Polvo 400 G", disponible: 207 },
{ nombre: "Ácido Fólico Folivital Tableta 0.4 Mg", disponible: 183 },
{ nombre: "Albendazolsuspensión 2g/100ml Frasco Con 20 Ml", disponible: 173 },
{ nombre: "Difenidol Biomitin Tabletas 25 Mg", disponible: 170 },
{ nombre: "Metoclopramida Biopram Tabletas Enbase Con 20", disponible: 160 },
{ nombre: "FD Lidocaine Hci With Epinephrine Solución 2% 1:100,000 Inyectable", disponible: 150 },
{ nombre: "Brubiol Ciprofloxacino Tabletas, 250 Mg", disponible: 148 },
{ nombre: "Vitamina A, C Y D, Retinol, Ácido Ascórbico, Colecalciferol, Solución 15ml, Gotero, Oral", disponible: 144 },
{ nombre: "Hioscina Tabletas 10 Mg, Oral", disponible: 143 },
{ nombre: "Dila-Tec Hidralazina Tabletas 10 Mg Oral", disponible: 136 },
{ nombre: "Indigon Metamizol Sódico Tabletas 500 Mg Oral", disponible: 135 },
{ nombre: "Dimopen Amoxicilia Capsulas 500 Mg", disponible: 123 },
{ nombre: "Histina Loratadina Tableta 10 Mg", disponible: 123 },
{ nombre: "Benzatina Bencilpenicilina, Bencilpenicilina Procaína Y Bencilpenicilina, Suspenesión 1,200000 UI", disponible: 116 },
{ nombre: "Albendazol Tabletas 200 Mg Caja Con 2 Tabletas Oral", disponible: 114 },
{ nombre: "Nistatina Tabletas 100,000 UI, Vaginal", disponible: 111 },
{ nombre: "Óxido De Zinc, Pasta 25 G", disponible: 110 },
{ nombre: "C-Messel, Ácido Ascóbico Tabletas 100mg", disponible: 108 },
{ nombre: "Dinitrato De Isisorbida Tabletas Sublinguales 5 Mg", disponible: 108 },
{ nombre: "Cloten Paracetamol, Cafeína, Fenilefrina, Clorfenamina, Tabletas, 500 Mg/25 Mg/5mg/4mg", disponible: 107 },
{ nombre: "Electrolitos Polvo Para Solición Sobre 20.5 G", disponible: 106 },
{ nombre: "Decatriol Calcitriol Capsulas 0.25 Mcg, Oral", disponible: 104 },
{ nombre: "Cyclofémina Medroxiprogesterona / Cipionato De Estradiol, Suspensión Inyectable 25mg/5 Mg", disponible: 102 },
{ nombre: "Cilicid Ácido Fólico Tabletas 5 Mg", disponible: 99 },
{ nombre: "Karim Optimum Jarabe 240 Ml Con Vitaminas, Minerales Y Amonoácido L-Lisina", disponible: 95 },
{ nombre: "Prochor Propranolol, Tableta 40 Mg Oral", disponible: 89 },
{ nombre: "Senósidos A-B, Tabletas, 8.6 Mg Oral", disponible: 89 },
{ nombre: "Farmarest Salbutamol Aerosol 100 Mg, Para Inhalación", disponible: 87 },
{ nombre: "Loexom Ambroxol, Tabletas 30 Mg", disponible: 87 },
{ nombre: "Bistatin-V Nistatina, Tableta 100,000 U, Vaginal", disponible: 86 },
{ nombre: "Messelzol Ketoconazol Tabletas 200 Mg", disponible: 86 },
{ nombre: "Padamina Clorfenamina, Tabletas 4 Mg", disponible: 86 },
{ nombre: "Gelprim Cápsulas Nifedipino 10 Mg Oral", disponible: 84 },
{ nombre: "Hidróxido De Aluminio, Hidróxido De Magnesio, Suspensón 3.70g / 4.00g Frasco Con 240 Ml", disponible: 80 },
{ nombre: "Ampitecno-T Ampicilina, Tabletas 500 Mg", disponible: 75 },
{ nombre: "Fenazopiridina Bioferina Tabletas 100 Mg, Oral", disponible: 72 },
{ nombre: "Hioscina Solución 20mg/ Ml Inyectable Caja Con 3 Ampolletas", disponible: 72 },
{ nombre: "Difenhistat Difenhidramina Solución 10 Mg/1 Ml Inyectable", disponible: 70 },
{ nombre: "Indometacina Biometacin Cápsula 25 Mg", disponible: 69 },
{ nombre: "Nibezvag Bezafibrato Tabletas 200 Mg", disponible: 69 },
{ nombre: "CloFHiven Dipropionato De Beclometasona Aerosol 50mg Para Inhalación", disponible: 68 },
{ nombre: "Espironolactona Biolactona Tabletas 25 Mg", disponible: 63 },
{ nombre: "Synbicort Budesonida/Formoterol, Turbuhaler 80 Mg/4.5 Mg Polvo Para Inhalación", disponible: 62 },
{ nombre: "Ácido Acetilsalicílico Tabletas 500 Mg", disponible: 61 },
{ nombre: "Estrógenos Conjugados Tableta 0.625 Mg", disponible: 60 },
{ nombre: "Bioral-V Nitrofural, Óvulos, Vagial", disponible: 57 },
{ nombre: "Doxiciclina Tableta 100 Mg", disponible: 57 },
{ nombre: "Nitrofurantoina Biofurin Capsulas 100 Mg Oral", disponible: 56 },
{ nombre: "Clioquinol Bionder-C Crema 3 G", disponible: 54 },
{ nombre: "Eritromicina Tableta 500 Mg", disponible: 53 },
{ nombre: "Brudifen Difenhidromina 250 Mg / 100 Ml", disponible: 52 },
{ nombre: "Biorenyn Salbutamol, Jarabe 40 Mg / 100 Ml Oral", disponible: 50 },
{ nombre: "Ácido Acetilsalicílico Tabletas 300 Mg, Efervecentes", disponible: 48 },
{ nombre: "Clindamicina Cigmadil, Cápsulas 300mg", disponible: 48 },
{ nombre: "Texoven Benzonatato, Cápsulas 100 Mg", disponible: 48 },
{ nombre: "RELVARE Furoato De Fluticasona / Vilanterol Polvo 100 Mg/25 Mg Para Inhalación", disponible: 47 },
{ nombre: "Benzatina Bencilpenicilina Suspensión 1 200 000 U, Inyectable", disponible: 44 },
{ nombre: "Hidroffen Hidrocortisona Crema 0.1 G / 100 G", disponible: 44 },
{ nombre: "Cloranfenicol Solución Gotas 0.5% 5 Ml", disponible: 43 },
{ nombre: "Semeterol, Fluticasona Aerosol 25 Mg, 50 Mg Para Inhalar", disponible: 43 },
{ nombre: "Alibour, Alosuan Polvo, Caja Con 12 Sobres Con 2.2 G", disponible: 42 },
{ nombre: "Balsedrina Dextrometorfano Jarabe 0.3 G / 100 Ml", disponible: 41 },
{ nombre: "Dexametasona Solución Inyectable 8mg/2ml", disponible: 41 },
{ nombre: "Klarix Claritromicina Tabletas 250 Mg", disponible: 40 },
{ nombre: "Dinitrato De Isosorbida Biordyn Tabletas 10 Mg", disponible: 36 },
{ nombre: "Tromodil-V Estrtógenos Conjugados Crema 62.5 Mg / 100g", disponible: 36 },
{ nombre: "Diclofenaco Solución 75 Mg/3ml Inyectable", disponible: 35 },
{ nombre: "Ikatin Gentamicina Solucion Inyectable 20mg/2ml", disponible: 35 },
{ nombre: "Ultibro Breezhaler, Indacaterol / Glicopirronio Polvo 110 Mg / 50 Mg", disponible: 35 },
{ nombre: "Cefalexina Cápsulas 50 Mg, Oral", disponible: 34 },
{ nombre: "Gentamicina 80 mg/2 Ml Inyectable", disponible: 32 },
{ nombre: "Glimepirida Glimal Tabletas 2 Mg, Oral", disponible: 29 },
{ nombre: "Lidocaina Solucion 20 Mg/Ml Inyectable Caja Con 5 Frascos", disponible: 29 },
{ nombre: "Ceftriaxona Solución 1g, Inyectable Via De Administración Intravenosa", disponible: 28 },
{ nombre: "Hipromelosa Solución 0.5%, Via De Administración Oftálmica", disponible: 28 },
{ nombre: "Loperamida Tarmin Tabletas 2 Mg Oral", disponible: 27 },
{ nombre: "Sayana Medroxiprogesterona Suspensión Inyectable, 104 Mg/0.65 Ml", disponible: 25 },
{ nombre: "Salbutamol Vetrivatox Solucion 5 Mg/Ml Nebulización", disponible: 20 },
{ nombre: "Calcio Bionokaltran Comprimidos 500mg Efervesentes", disponible: 19 },
{ nombre: "Dispositivo Intrauterino, T De Cobre, 380 A", disponible: 18 },
{ nombre: "Neomicina, Polimixina B, Gramicina. Polixin Ofteno Solución 1.750mg/5000UI/0.025 Mg/Ml Frasco Gotero", disponible: 16 },
{ nombre: "Cloranfenicol Unguento Tubo 5mg/G Oftálmico", disponible: 15 },
{ nombre: "Desogestrel And Ethinyl Estradiol Tablets Usp 0.15mg/0.03mg", disponible: 15 },
{ nombre: "Difenidol Solición 40 Mg/2 Ml, Inyectable", disponible: 15 },
{ nombre: "Lantus Insulina Glargina Solución Inyectable Subcutánea Caja Con 5 Plumas", disponible: 15 },
{ nombre: "Metamizol Sódico Solución 1 G/2 Ml Inyectable", disponible: 12 },
{ nombre: "Levonorgestrel Tabletas 0.75mg Oral", disponible: 10 },
{ nombre: "Prevepost Noretisterona, Estradiol Solución Inyectable 50mg/5mg", disponible: 10 },
{ nombre: "Bromuro De Ipratropio Salbutamol 0.5 Mg/2.5 Mg Para Nebulización 2.5 Ml Caja Con 10 Ampolletas", disponible: 9 },
{ nombre: "Ketoprofeno Cápsulas Oral 100 Mg", disponible: 6 },
{ nombre: "Ceretec Cinarizina Tabletas 75 Mg, Oral", disponible: 4 },
{ nombre: "Sertraline Amarox Filmomhulde Tabletten 50 Mg", disponible: 4 },
{ nombre: "Carbón Activado Polvo Oral Para Suspensión", disponible: 3 },
{ nombre: "Espironolactona Biolactona Tableta 25mg", disponible: 3 },
{ nombre: "Evra Norelgestromina Parche, 0.60 Mg, 6.00 Mg Liberación Prolongada", disponible: 3 },
{ nombre: "Hipermessel Metildopa Tabletas, 250 Mg Oral", disponible: 3 },
{ nombre: "Jadelle Levonorgestrel, Implante 75 Mg Inyectable", disponible: 3 },
{ nombre: "Mirena Levonorgestrel, Polvo 52.00 Mg En Dispositivo Intrauterino", disponible: 3 },
{ nombre: "Metoprolol Tableta 100 Mg", disponible: 2 },
{ nombre: "ZK - INA Spray Lidocaine Solution 10% 10 Mg / Dose", disponible: 2 },
{ nombre: "Alzoprim Alopurino Tabletas 300 Mg", disponible: 1 },
{ nombre: "Beteral, Sulfametoxazol, Trimetoprima, Tableta 400 Mg, 80 Mg Oral", disponible: 1 },
{ nombre: "Bromuro De Pinaverio, 100 Mg", disponible: 1 },
{ nombre: "Glucosa Solición 5% Inyectable Frasco Con 1000 Ml", disponible: 1 },
{ nombre: "Glucosa Solución 5%, Inyectable, Frasco con 500 Ml", disponible: 1 },
{ nombre: "Itraconazol, Zitriasol Cápsulas 100 Mg Oral", disponible: 1 },
{ nombre: "Pioglitazona Tableta 15 Mg Oral", disponible: 1 },
{ nombre: "Solución Harmann Solución Inyectable, Frasco Con 1000 Ml", disponible: 1 },
{ nombre: "Antivipmyn Faboterápico Polivalente Antiviperino", disponible: 0 },
{ nombre: "Fluoning Levofloxacino Tableta 750 Mg, Oral", disponible: 0 },
{ nombre: "Fluoxetina Tableta 20 Mg, Oral", disponible: 0 },
{ nombre: "Glibenclamida Tableta 5 Mg Oral", disponible: 0 },
{ nombre: "Levofloxacino Tableta 750 Mg, Oral", disponible: 0 },
{ nombre: "Metformina Tableta 850 Mg", disponible: 0 },
{ nombre: "Nediclon Diclofenaco, Oral Tabletas 100 Mg, Liberación Prolongada", disponible: 0 },
{ nombre: "Nifedipino Comprimnidos 30 Mg Liberación Prolongada", disponible: 0 },
{ nombre: "Spiriva Bromuri De Tiotropio, Polvo 18 Mcg Para Inhalación", disponible: 0 },
{ nombre: "Trelegy, Fluticasona, Umeclidinio, Vilanterol, Polvo 100 Mcg, 62.5 Mcg, 25 Mcg Para Inhalación", disponible: 0 },
{ nombre: "Tribedoce Tlamina, Piridoxina, Cianoclbalamina Tabletas 100mg, 5 Mg, 50 Mcg", disponible: 0 }
    // Agrega más medicamentos según sea necesario
];

function buscarMedicamento() {
    const query = document.getElementById("search").value.toLowerCase();
    const resultsDiv = document.getElementById("results");
    resultsDiv.innerHTML = "";

    if (query.trim() === "") {
        return; // No mostrar nada si el input está vacío
    }

    const resultados = medicamentos1.filter(med => med.nombre.toLowerCase().includes(query));

    if (resultados.length > 0) {
        resultados.forEach(med => {
            const div = document.createElement("div");
            div.classList.add("medicine");
            div.textContent = `${med.nombre} - Disponible: ${med.disponible}`;
            resultsDiv.appendChild(div);
        });
    } else {
        resultsDiv.textContent = "No se encontraron medicamentos.";
    }
}